# ==========================================
# 1. Configuração do Banco de Dados (Supabase)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.fsllbkajuxiqmawrlucl
spring.datasource.password=ademiconportobelogui

# ==========================================
# 2. Configurações do Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# 3. Servidor de E-mail (Recuperação de Senha)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# ATENÇÃO: Preenche com o teu e-mail real e a "Senha de App" (não a senha normal)
spring.mail.username=teu-email-oficial@gmail.com
spring.mail.password=sua-senha-de-app-da-google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true